# Generated by Django 5.2.6 on 2025-09-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_icecream_cart_wishlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='ice_cream',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='icecream',
            name='image_url',
        ),
        migrations.AddField(
            model_name='icecream',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='icecream',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='icecream_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='icecream',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
