# Generated by Django 5.2.6 on 2025-09-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_wishlist_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icecream',
            name='image',
        ),
        migrations.AddField(
            model_name='icecream',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='price',
            field=models.FloatField(),
        ),
    ]
